<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Banking.Application/Banking.Application.csproj" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="Confluent.Kafka" Version="2.16.0" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
